### ISSUE TITLE
Problème d'édition d'un bien sans mouvements

### ISSUE THREAD

**Issue by hubr64** [hubr64/easyloc.github.io#15]
Lorsqu'on cherche à afficher la fiche d'un bien sans mouvement on a une erreur d'exécution.
L'erreur dans la console est la suivante :
```
ERROR TypeError: Cannot read properties of undefined (reading '2022')
    at t.computeChartOptionsForSimpleBien (main.a84260fead65367a.js:1:923520)
    at t.ngOnInit (main.a84260fead65367a.js:1:914232)
    at Tt (main.a84260fead65367a.js:1:24465)
    at S_ (main.a84260fead65367a.js:1:24296)
    at hp (main.a84260fead65367a.js:1:24023)
    at BT (main.a84260fead65367a.js:1:53953)
    at _ (main.a84260fead65367a.js:1:53798)
    at template (main.a84260fead65367a.js:1:1487880)
    at qT (main.a84260fead65367a.js:1:58267)
    at X1 (main.a84260fead65367a.js:1:57058)
````
Il semblerait donc qu'on cherche à calculer des statistiques mais sans valeurs fournies, il y a un bug d'exécution.

Dans la fonction d'édition de la fiche on a bien des staistiques qui s'affiche mais ce ne sont pas celles du bien (a priori ce sont les stats globales). 

Il faut robustifier les algos pour prendre en compte l'absence de mouvements :

- soit en inhibant l'affichage des stats
- soit en mettant tout à zéro

**Comment by hubr64** [comment]
Au final, correction des scripts pour préremplir les données de tous les biens à 0 pour l'année courante même ceux sans mouvement. Permet de garantir que les graphs seront traités correctement.
